services:
  frontend:
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]

  bff:
    ports:
      - "8000:8000"
    volumes:
      - ./services/bff/app:/app/app
      - ./services/bff/tests:/app/tests
    environment:
      LOG_LEVEL: debug
    command:
      [
        "sh",
        "-c",
        "uv run uvicorn app.main:app --host 0.0.0.0 --port $$PORT --reload",
      ]

  auth-service:
    volumes:
      - ./services/auth/app:/app/app
      - ./services/auth/tests:/app/tests
      - ./services/auth/alembic:/app/alembic
      - ./services/auth/alembic.ini:/app/alembic.ini
    command:
      [
        "sh",
        "-c",
        "uv run uvicorn app.main:app --host 0.0.0.0 --port $$PORT --reload",
      ]

  ledger-service:
    ports:
      - "8002:8002"
    volumes:
      - ./services/ledger/app:/app/app
      - ./services/ledger/tests:/app/tests
      - ./services/ledger/alembic:/app/alembic
      - ./services/ledger/alembic.ini:/app/alembic.ini
    environment:
      SQLALCHEMY_ECHO: "true"
      PROFILE_REQUESTS: "true"
    command:
      [
        "sh",
        "-c",
        "uv run uvicorn app.main:app --host 0.0.0.0 --port $$PORT --reload",
      ]

  postgres-ledger:
    ports:
      - "5432:5432"
